pan_controller:
  controller:
    package: dynamixel_controllers
    module: joint_torque_controller
    type: JointTorqueController
  joint_name: pan_joint
  joint_speed: 1.5
  motor:
    id: 3
    init: 512
    min: 380
    max: 560
